### ISSUE TITLE
TypeError thrown for mov instruction

### ISSUE THREAD

**Issue by ddash-ct** [dod-cyber-crime-center/rugosa#1]
Using IDA 8.1 as a backend disassembler, with sample SHA256 `12331809c3e03d84498f428a37a28cf6cbb1dafe98c36463593ad12898c588c9`, encountering the following error on a `mov ebx, ds:SetFilePointer` instruction.

```
[!] Failed to execute address 0x401724: mov     ebx, ds:SetFilePointer
Traceback (most recent call last):
  File "C:\Python\Python39\lib\site-packages\rugosa\emulation\instruction.py", line 202, in execute
    self._execute()
  File "C:\Python\Python39\lib\site-packages\rugosa\emulation\x86_64\instruction.py", line 34, in _execute
    super()._execute()
  File "C:\Python\Python39\lib\site-packages\rugosa\emulation\instruction.py", line 178, in _execute
    opcode_func(self._cpu_context, self)
  File "C:\Python\Python39\lib\site-packages\rugosa\emulation\x86_64\opcodes.py", line 1131, in _mov
    operands[0].value = opvalue2
  File "C:\Python\Python39\lib\site-packages\rugosa\emulation\x86_64\operands.py", line 178, in value
    super(x86_64Operand, self.__class__).value.__set__(self, value)
  File "C:\Python\Python39\lib\site-packages\rugosa\emulation\operands.py", line 214, in value
    self._cpu_context.registers[reg.name] = value
  File "C:\Python\Python39\lib\site-packages\dragodis\ida\operand_value.py", line 46, in name
    return self._ida._ida_idp.get_reg_name(self._reg, self._width).lower()
rpyc.core.netref.type: 'NoneType' object has no attribute 'lower'
```

Suspect something is wrong with the `self._reg` or `self._width`

**Comment by ddash-ct** [comment]
This is also occurring for sample SHA256 `e453c1b908c18881bec40c6ae1e85bf64d12ef84d7a9a704cf957af83252af4e`, rugosa version 0.7.0:
```
[!] Failed to execute address 0x410C37: cmp     byte ptr [eax+19h], 0
Traceback (most recent call last):
  File "C:\Python\Python39\lib\site-packages\rugosa\emulation\instruction.py", line 202, in execute
    self._execute()
  File "C:\Python\Python39\lib\site-packages\rugosa\emulation\x86_64\instruction.py", line 34, in _execute
    super()._execute()
  File "C:\Python\Python39\lib\site-packages\rugosa\emulation\instruction.py", line 178, in _execute
    opcode_func(self._cpu_context, self)
  File "C:\Python\Python39\lib\site-packages\rugosa\emulation\x86_64\opcodes.py", line 270, in CMP
    cpu_context.jcccontext.update_flag_opnds(["cf", "af", "zf", "sf", "of", "pf"], operands)
  File "C:\Python\Python39\lib\site-packages\rugosa\emulation\cpu_context.py", line 69, in update_flag_opnds
    self.flag_opnds[flag] = [OperandLite(opnd.ip, opnd.idx, opnd.text, opnd.value) for opnd in opnds]
  File "C:\Python\Python39\lib\site-packages\rugosa\emulation\cpu_context.py", line 69, in <listcomp>
    self.flag_opnds[flag] = [OperandLite(opnd.ip, opnd.idx, opnd.text, opnd.value) for opnd in opnds]
  File "C:\Python\Python39\lib\site-packages\rugosa\emulation\x86_64\operands.py", line 138, in value
    return super().value
  File "C:\Python\Python39\lib\site-packages\rugosa\emulation\operands.py", line 169, in value
    addr = self.addr
  File "C:\Python\Python39\lib\site-packages\rugosa\emulation\x86_64\operands.py", line 104, in addr
    addr = self._calc_displacement()
  File "C:\Python\Python39\lib\site-packages\rugosa\emulation\x86_64\operands.py", line 28, in _calc_displacement
    addr = self.base + self.index * self.scale + self.offset
  File "C:\Python\Python39\lib\site-packages\rugosa\emulation\operands.py", line 118, in base
    value = self._cpu_context.registers[base_reg.name]
  File "C:\Python\Python39\lib\site-packages\dragodis\ida\operand_value.py", line 66, in name
    return self._ida._ida_idp.get_reg_name(self._reg, self._width).lower()
rpyc.core.netref.type: 'NoneType' object has no attribute 'lower'
```

**Comment by dc3-tsd** [comment]
This should have been fixed in a past release.  Please let us know if you are still having problems.
