### ISSUE TITLE
TypeMap error on fld instruction in IDA

### ISSUE THREAD

**Issue by ddash-ct** [dod-cyber-crime-center/rugosa#6]
Using sample MD5 `e7f46144892fe5bdef99bdf819d1b9a6`, a `KeyError` and subsequent `RuntimeError` are thrown at address 0x4048d7 for a `fld` instruction when using IDA.  This error is not observed when using Ghidra as the disassembler.

The following stack trace is observed:
```
Traceback (most recent call last):
  File "C:\Python\Python39\lib\site-packages\dragodis\ida\operand.py", line 71, in type
    return self._type_map[op_type]
KeyError: 11

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "<string>", line 8, in <module>
  File "C:\Python\Python39\lib\site-packages\rugosa\emulation\cpu_context.py", line 281, in execute
    self.instruction.execute()
  File "C:\Python\Python39\lib\site-packages\rugosa\emulation\instruction.py", line 208, in execute
    var = operand._operand.variable
  File "C:\Python\Python39\lib\site-packages\dragodis\ida\operand.py", line 101, in variable
    value = self.value
  File "C:\Python\Python39\lib\site-packages\dragodis\ida\operand.py", line 190, in value
    operand_type = self.type
  File "C:\Python\Python39\lib\site-packages\dragodis\ida\operand.py", line 175, in type
    type = super().type
  File "C:\Python\Python39\lib\site-packages\dragodis\ida\operand.py", line 73, in type
    raise RuntimeError(f"Unexpected operand type: {op_type}")
RuntimeError: Unexpected operand type: 11

Failed to execute address 0x4048D7: fld     ds:flt_66D9D4
Traceback (most recent call last):
  File "C:\Python\Python39\lib\site-packages\dragodis\ida\operand.py", line 71, in type
    return self._type_map[op_type]
KeyError: 11

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:\Python\Python39\lib\site-packages\rugosa\emulation\instruction.py", line 202, in execute
    self._execute()
  File "C:\Python\Python39\lib\site-packages\rugosa\emulation\x86_64\instruction.py", line 34, in _execute
    super()._execute()
  File "C:\Python\Python39\lib\site-packages\rugosa\emulation\instruction.py", line 178, in _execute
    opcode_func(self._cpu_context, self)
  File "C:\Python\Python39\lib\site-packages\rugosa\emulation\x86_64\fpu_opcodes.py", line 247, in FLD
    value = orig_value = operands[0].value if operands else None
  File "C:\Python\Python39\lib\site-packages\rugosa\emulation\x86_64\operands.py", line 142, in value
    if self.type == OperandType.memory:
  File "C:\Python\Python39\lib\site-packages\rugosa\emulation\operands.py", line 69, in type
    return self._operand.type
  File "C:\Python\Python39\lib\site-packages\dragodis\ida\operand.py", line 175, in type
    type = super().type
  File "C:\Python\Python39\lib\site-packages\dragodis\ida\operand.py", line 73, in type
    raise RuntimeError(f"Unexpected operand type: {op_type}")
RuntimeError: Unexpected operand type: 11
```

**Comment by ddash-ct** [comment]
Issue is fixed
